requires 'JSON::PP';
requires 'Data::Printer';
requires 'Term::ANSIColor';
requires 'Net::MAC::Vendor';
requires 'Path::Tiny';
requires 'IPC::Run3';
requires 'Time::HiRes';
requires 'UUID::Tiny';
requires 'Hash::Merge';
